#!/usr/bin/env bash
# Shell Example — variables, functions, conditionals, loops
# Hotakus's Nocturne Theme Preview

set -euo pipefail

APP_NAME="nocturne"
VERSION="1.0.0"
DEBUG=${DEBUG:-false}

# --- Function ---
log() {
  local level="$1"
  local message="$2"
  local ts
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  printf "[%s] [%s] %s\n" "$ts" "$level" "$message"
}

# --- Variable expansion ---
CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/$APP_NAME/config.json"

if [[ ! -f "$CONFIG_FILE" ]]; then
  log "WARN" "Config not found at $CONFIG_FILE, using defaults"
fi

# --- Array ---
TARGETS=("api" "worker" "scheduler")
SELECTED=()

for target in "${TARGETS[@]}"; do
  if [[ "$target" != "scheduler" ]]; then
    SELECTED+=("$target")
  fi
done

log "INFO" "Selected targets: ${SELECTED[*]}"

# --- Case ---
MODE="${1:-dev}"
case "$MODE" in
  dev)
    log "INFO" "Running in development mode"
    ;;
  prod)
    log "INFO" "Running in production mode"
    ;;
  *)
    log "ERROR" "Unknown mode: $MODE"
    exit 1
    ;;
esac

# --- Arithmetic ---
COUNT=0
while [[ $COUNT -lt 3 ]]; do
  log "DEBUG" "Iteration $COUNT"
  COUNT=$((COUNT + 1))
done

# --- Process substitution & pipe ---
echo -e "line1\nline2\nline3" | while read -r line; do
  log "INFO" "Read: $line"
done

# --- Here-doc ---
cat <<EOF > /tmp/nocturne-test.txt
Generated by $APP_NAME v$VERSION
Mode: $MODE
Targets: ${SELECTED[*]}
EOF

log "SUCCESS" "All done (pid $$)"
exit 0
